name: Release job

on:
  # Every Friday at 00:00 UTC
  schedule:
    - cron: '0 0 * * 5'

jobs:
  build-app:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Clone Repository (Latest)
        uses: actions/checkout@v4.1.4
        with:
          repository: 'disbxys/boardy3'
          fetch-depth: 0
        if: github.event.inputs.git-ref == ''
      - name: Clone Repository (Custom Ref)
        uses: actions/checkout@v4.1.4
        if: github.event.inputs.git-ref != ''
        with:
          repository: 'disbxys/boardy3'
          fetch-depth: 0
          ref: ${{ github.event.inputs.git-ref }}

      - name: Get previous release
        id: last_release
        uses: InsonusK/get-latest-release@v1.1.0
        with:
          myToken: ${{ github.token }}
          exclude_types: "draft|prerelease"
          view_top: 1

      - name: Prepare build
        run: |
          set -e

          commit_count=$(git rev-list --count HEAD)
          echo "COMMIT_COUNT=$commit_count" >> $GITHUB_ENV
          current_sha=$(git rev-parse --short HEAD)
          echo "CURRENT_SHA=$current_sha" >> $GITHUB_ENV

          prev_commit_count=$(echo "${{ steps.last_release.outputs.tag_name }}" | sed -e "s/^r//")
          commit_count_diff=$(expr $commit_count - $prev_commit_count)

          # If there are less than 3 new commits, exit without creating a release.
          if [ $commit_count_diff -lt 3 ]; then
            echo "Less than 2 new commits since the last release. Existing without creating a release."
            exit 0
          fi

          prev_release_sha=$(git rev-parse --short HEAD~$commit_count_diff)
          echo "PREV_RELEASE_SHA=$prev_release_sha" >> $GITHUB_ENV

          echo "COMMIT_LOGS<<{delimiter}
          $(curl -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/disbxys/boardy3/compare/$prev_release_sha...$current_sha" \
            | jq '[.commits[]|{message:(.commit.message | split("\n")), username:.author.login}]' \
            | jq -r '.[]|"- \(.message | first) (@\(.username))"')
          {delimiter}" >> $GITHUB_ENV

      - name: Create release
        uses: softprops/action-gh-release@v2.0.4
        with:
          tag_name: r${{ env.COMMIT_COUNT }}
          name: Boardy3 r${{ env.COMMIT_COUNT }}
          body: |
            ### Commits

            https://github.com/disbxys/boardy3/compare/${{ env.PREV_RELEASE_SHA }}...${{ env.CURRENT_SHA }}

            ${{ env.COMMIT_LOGS }}

          draft: ${{ github.event.inputs.dry-run != '' }}
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Prune old releases
        uses: dev-drprasad/delete-older-releases@v0.3.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          keep_latest: 28
          delete_tags: true